# Generated by Django 6.0.3 on 2026-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('stock_level', models.IntegerField()),
                ('status', models.CharField(default='notified', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Stock Bajo',
                'verbose_name_plural': 'Alertas de Stock Bajo',
                'db_table': 'low_stock_alerts',
            },
        ),
    ]
