# Generated by Django 6.0.3 on 2026-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockalert',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
