# Generated by Django 6.0.3 on 2026-03-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_agent', '0002_lowstockalert_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('provider_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_orders',
            },
        ),
        migrations.AlterModelOptions(
            name='lowstockalert',
            options={},
        ),
    ]
