# Generated by Django 6.0.3 on 2026-03-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_agent', '0003_providerorder_alter_lowstockalert_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockalert',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
