# Generated by Django 6.0.3 on 2026-03-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_agent', '0004_lowstockalert_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
