# Generated by Django 6.0.3 on 2026-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_agent', '0005_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockalert',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
